#!/usr/bin/env python
# -*- coding: utf-8 -*-

RESOURCE_CORE = {

	# General
	'priref':'priref',
	'record':'',

	'title':'resourceDublinCore_title-title', 
	'author.name':'resourceDublinCore_creators',
	'author.name-name':'',
    'keyword.contents-term':'resourceDublinCore_subject', 
    'abstract':'resourceDublinCore_description-term',
    'publisher':'resourceDublinCore_publishers', 
    'publisher-name':'',
    'contributor':'resourceDublinCore_contributor-contributor',
    'contributor-name':'',
    'year_of_publication':'resourceDublinCore_date', 
    'material_type':'',
    'material_type-term':'resourceDublinCore_resourceType',
    'dimensions':'resourceDublinCore_format-term', 
    'digital_reference':'resourceDublinCore_identifier-term',
    'sort_year':'resourceDublinCore_sortYear_sortYear', 
    'source':'resourceDublinCore_source-term',
    'language_code':'',
    'language_code-term':'resourceDublinCore_language', 
    'relation':'resourceDublinCore_relation-term',
    'coverage':'resourceDublinCore_coverage-term', 
    'rights':'resourceDublinCore_rights-term',

    'reproduction-reproduction.reference-reference_number':'reproductions_reproduction-reference',
    'reproduction-reproduction.reference-image_reference':'reproductions_reproduction-identifierURL',
    'reproduction-reproduction.notes':'reproductions_reproduction-notes',
    'exhibition':'',
    'exhibition-exhibition':'exhibitionsAuctionsCollections_exhibition-exhibitionName', 
    'exhibition-exhibition.notes':'exhibitionsAuctionsCollections_exhibition-notes', 
    'auction.name':'',
    'auction.name-auction':'exhibitionsAuctionsCollections_auction-auctionName',
    'auction.notes':'exhibitionsAuctionsCollections_auction-notes',

    #'':'exhibitionsAuctionsCollections_collection-collectionName',
    'collection.notes':'exhibitionsAuctionsCollections_collection-notes',
    'object.object_number':'linkedObjects_linkedObjects-objectNumber',

    'copy.number':'',
    'shelf_mark':'copiesAndShelfMarks_defaultShelfMark', 
    'copy.number-copy_number':'copiesAndShelfMarks_copyDetails-copyNumber',
    'copy.number-shelfmark':'copiesAndShelfMarks_copyDetails-shelfMark',
    'copy.shelfmark':"",
    'loan_category':'',
    'loan_category-term':'copiesAndShelfMarks_copyDetails-loanCategory',
    'site':'',
    'site-term':'copiesAndShelfMarks_copyDetails-site',
    'copy.number-location.note':'copiesAndShelfMarks_copyDetails-locationNotes',

    'datasets.collect':'',
	'datasets.collect-text':'',

    "reproduction":"",
    "reproduction-reproduction.format":"",
    "reproduction-reproduction.reference":"",
    "reproduction-reproduction.reference-format":"",
    "reproduction-reproduction.reference-production_date":"",
    "reproduction-reproduction.reference-reproduction_type":"",
    "reproduction-reproduction.reference-creator":"",
    "reproduction-reproduction.date":"",
    "reproduction-reproduction.type":"",
    "reproduction-reproduction.creator":"",
    "reproduction-reproduction.identifier_URL":"",
    "object.object_number-object_number":"",
    "object.object_number-object_name":"",
    "object.object_number-title":"",
    "object.object_number-creator":"",
    "object.object_name":"",
    "copy.serial.missing":"",
    "internal_link_priref":"",
    "internal_link_title":"",
    "object.title":"",
    "auction.place":"",
    "auction.number":"",
    "auction.auctioneer":"",
    "auction.startdate":"",
    "auction.enddate":"",
    "auction.name-place":"",
    "auction.name-auction_number":"",
    "auction.name-auctioneer":"",
    "auction.name-date_early":"",
    "auction.name-date_late":"",
    "auction.name-commissair-priseur":"",
    "auction.name-location":"",
    "auction.name-collector":"",
    "auction.commissair-priseur":"",
    "auction.location":"",
    "object.creator":"",
    "copy.status":"",

    "copy.status":"",
    "copy.status-text":"",
    "copy.remarks":"",
    "copy.number-serial.holding":"",
    "copy.number-serial.missing":"",
    "copy.number-loan_status":"",
    "copy.number-loan_status-text":"",
    "copy.number-L1":"",
    "copy.number-la":"",
    
    "keyword.contents":"",
    "keyword.contents-term.code":"",
    "auction.collector":"",

    "exhibition-exhibition.date.start":"",
    "exhibition-exhibition.date.end":"",
    "exhibition-old.exhibition.date.end":"",
    "exhibition-exhibition":"",
    "exhibition-exhibition-date.start":"",
    "exhibition-exhibition-date.end":"",
    "exhibition-exhibition-title":"",
    "exhibition-exhibition-organiser":"",
    "exhibition-exhibition-venue":"",
    "exhibition-exhibition-venue.place":"",
    "exhibition-exhibition.organiser":"",
    "exhibition-old.exhibition.date.start":"",
    "exhibition-exhibition.venue":"",
    "exhibition-exhibition.place":"",
    "copy.serial.holding":"",

    'Edit':'',
    'Edit-edit.name':'',
    'Edit-edit.time':'',
    'Edit-edit.date':'',
    'Edit-edit.source':'',
    'Edit-edit.notes':'',
    'input.source':'',
    'input.date':'',
    'input.name':'',
    'input.time': '',
}

